# Configure the database used when in the development environment
development:
  adapter: postgresql
  encoding: unicode
  database: comics_development
  pool: 10
  username:
  password:

# Configure the database used when in the test environment
test:
  adapter: postgresql
  encoding: unicode
  database: comics_test
  pool: 5
  username:
  password:

# Configure the database used when in the production environment
production:
  adapter: postgresql
  encoding: unicode
  database: comics_production
  pool: 5
  username:
  password:
